//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib_TMU.h                                                                           		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximLib/MaximLib_TMU.h $
*   Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*   Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:
*		Maxim library header file for TMU
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History                                                    
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	Maximlib_TMU.h
@brief	Maxim library file for TMU
**************************************************************************************************************************************************************/

#ifndef MAXIMLIB_TMU_H
#define MAXIMLIB_TMU_H

	PinListData Maximqtmumt( PME_INT tmu, int mode, int timeout, int start = -1, int stop = -1, int slice = 1 );
	PinListData Maximqtmumt( int tmu, int mode, int timeout, int start = -1, int stop = -1, int slice = 1 );
	//int Maximqtmuarm( int tmu, LPCTSTR source, int count = 1, int trigger = QTMU_EDGE, int slope = QTMU_NEG );

	int Maximqtmuarm( int tmu, LPCTSTR source, int count = 1, int trigger = QTMU_EDGE, int slope = QTMU_NEG );
	int Maximqtmuinit( int tmu );
	int Maximqtmumode( int tmu, int mode, int ArmOut = QTMU_ARMOUTOFF );
	int Maximqtmustart( int tmu, LPCTSTR pinName, int pinType, int slope, int Holdoff = 0, int RetriggerHoldoff = QTMU_NOFILTER, double AnalogLevel = 0.0 );
	int Maximqtmustat( int tmu, QTMU_STR* qtmu_data, int StartSlice = 1, int Revision = QTMU_STR_REV );
	int Maximqtmustop( int tmu, LPCTSTR pinName, int pinType, int slope, int Holdoff = 0, int RetriggerHoldoff = QTMU_NOFILTER, double AnalogLevel = 0.0 );

namespace Maxim
{
	int Connect_TMU_Pin_To_Site(PME_INT pmeTMUPin, int iSite);	//Tell the "No Site" pin that it is physically connected to this site.  Required for the Measurement and Datalog functions.
}

#endif