//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib_Deglitch.H                                                                            		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximLib/MaximLib_Deglitch.h $
*   Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*   Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:  
*		Maxim library file for Deglitch
*		Maxim library written and maintained by:								 
*			Daniele Ghezzi(Daniele.Ghezzi@MaximIntegrated.com)
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History
*		
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	Maximlib_Deglitch.h
@brief	Maxim library file for Deglitch  
**************************************************************************************************************************************************************/
// Following is documentation to be used by Doxygen to create help files.
/************************************************************************************************************************************************************For*Doxygen**//**
@page guideDeglitch Deglitch Assistant
@details 
## Overview ##
The __Deglitch Assistant__ is a  hardware and software toolset used to ease the deglitching of test programs making use of a scope equipped with TRIGGER OUT connector. 
- The advantage of using the Deglitch Assistant with respect to a bare hands approach is to implement a quasi-real time  break-on-glitch technology
	- upon glitch detected by the scope, the program gets stopped in breakpoint and it is possible to come back immediately to the line of the source code that created the spike. 
- The time spent to find the guilty instructions in the test program source code is therefore practically nulled.

## Implementation ##
The documentation in the link below should be all you need to know in order to use the deglitch assistant on the ETS-88.

[ETS-88 Deglitch Assistant.pdf](https://confluence.maxim-ic.com/download/attachments/25103545/ETS-88_Deglitch_Assistant.pdf)

## How to build an ETS88 deglitch cable ##
The document in the link below covers the components needed, instructions on how to build an ETS88 deglitch cable, and the theory of how an ETS88 Deglitch cable works.

[ETS88_Deglitch_Cable_Build_Documentation.pdf](https://confluence.maxim-ic.com/download/attachments/25103545/ETS88_Deglitch_Cable_Build_Documentation.pdf)

## See Also ##
A general overview of deglitch assistants on multiple platforms can be found at: [Deglitch Assistant Home Page](http://cdserver1.testeng.maxim-ic.com/~ghezzi_d/Support_files/deglitch_assistant/Deglitch_assistant.htm)
**************************************************************************************************************************************************************/

#ifndef MAXIMLIB_DEGLITCH_H
#define MAXIMLIB_DEGLITCH_H
//#ifdef MAXIM_DEGLITCH
void DeglitchBreakpoint(void);
namespace Maxim
{
	namespace Deglitch
	{
		void deglitch_Init(void);
		void glitch_handling(void);
	}
}
#endif
//#endif