//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib_Exec.h                                                                           		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximLib/MaximLib_Exec.h $
*	Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*	Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:
*		Maxim library header file for Test Control functions
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History                                                    
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	Maximlib_Exec.h
@brief	Maxim library file for Test Control functions
**************************************************************************************************************************************************************/

#ifndef MAXIMLIB_EXEC_H
#define MAXIMLIB_EXEC_H


	namespace Maxim
	{
		namespace Exec
		{
				BOOL Lib_UserInit(int iNumSites, bool bLoadVector, bool bInitMeter = false, int iRealTimeDatalogSwitch = -1);
				BOOL Lib_UserExit();
				BOOL Lib_OnTestInitPre();
				BOOL Lib_OnTestInitPost();
				BOOL Lib_OnTestExitPre();
				BOOL Lib_OnTestExitPost();
				BOOL Lib_OnTestStartupPre(BOOL bTimeTests);
				BOOL Lib_OnTestStartupPost();
				BOOL Lib_OnTestCompletionPrePowerDown();
				BOOL Lib_OnTestCompletionPostPowerDown();
				BOOL Lib_OnLogData(int site, datalog_info_t& info);
				BOOL Lib_OnFailSitePrePowerDown(int site);
				BOOL Lib_OnFailSitePostPowerDown(int site);
				int Lib_OnSot(int SotValue, int UserSwitchSite0, int UserSwitchSiteMax, int UserIntLoopCount, int UserIntLoopDelayms, bool bCheckerPassed );
				BOOL Lib_OnUtilError(int errnum);
				BOOL Lib_OnInterlock(ULONG intlocks);
	
				BOOL Lib_GetTestLimits(PDS_DOUBLE &lolimit, PDS_DOUBLE &hilimit);
				int Lib_Contact(int & DSIndex);
		}

		namespace System
		{
			typedef enum 
			{	//Define Sector numbers
				ETSSectorUnknown = 0,
				ETSSector1A = 1,	//Sector 1A is defined as 1 to satisfy the MaximDLL standard.
				ETSSector1B,
				ETSSector2A,		//Maxim testers currently only have hardware for sectors 1A and 1B.
				ETSSector2B,
			}ETSSector;
			
			ETSSector GetETSSector();
			ETSSector GetEshellSector();
			std::string GetETSSectorString();		

			bool bOnline();
		}
		bool Operator();
	}

		
#endif
