//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib_DPAT.H                                                                          		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximLib/MaximLib_DPAT.h $
*   Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*   Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:  
*		Maxim library file for DPAT functions
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History
*		See Maximlib.h file.
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	MaximLib_DPAT.h
@brief	Maxim library file for DPAT functions
**************************************************************************************************************************************************************/

// Following is documentation to be used by Doxygen to create help files.
/************************************************************************************************************************************************************For*Doxygen**//**
@section quickStartDPAT DPAT Quick Start
@details 
Dynamic Part Average Testing (DPAT) for ETS-88 testers  developed by [TEST R&D](https://confluence.maxim-ic.com/pages/viewpage.action?pageId=25103017). @n
This is part of Maxim's In-house [DPAT](https://confluence.maxim-ic.com/display/TE/Maxim+DPAT) solution.

## What is DPAT? ##
*Please see Maxim's In-house [DPAT](https://confluence.maxim-ic.com/display/TE/Maxim+DPAT) page and the [Galaxy](https://confluence.maxim-ic.com/display/GLX/Galaxy) page.

## Setup DPAT ##
- All DPAT functions are in the namespace Maxim::DPAT
- You should update your program to use the latest [ETS-88 Libraries](https://confluence.maxim-ic.com/display/ETS88/ETS-88+Libraries)


In Maxim_UserInit() 
-# Add per test DPAT_add_test(function number, test number, method, initial samples, window size, scalar) or 
	DPAT_add_test(function number, test number, method, initial samples, window size, scalar low, scalar high)
	-# See Maxim [DPAT] for details of parameters.
-# Turn on DPAT for test steps that should use DPAT (enabled for FT, disabled for QA).  
	@code
		if (Maxim::Operator()&&Maxim::bTest_Step_Is("FT_ROOM"))
		{
			Maxim::DPAT::DPAT_add_test(200,"Stdev",30,100,6.0);
			Maxim::DPAT::DPAT_add_test(201,"Quartile",30,100,6.0);
			Maxim::DPAT::DPAT_add_test(202,"Stdev",30,100,4.0,7.0);
		}
	@endcode
	@note Maxim::Operator() is true when running from the [ETS-88 Production Loader](https://confluence.maxim-ic.com/display/ETS88/ETS-88+Production+Loader)
-# If product is a WLP, you can set an initial sample bin to be able to retest: 
	@code 
		Maxim::DPAT::DPAT_set_sample_bin(4) 
	@endcode
-# Make sure to add the appropriate bin to your Datasheet.
-# Add DPAT test to the end of your program.  This can be in your last function or you can create a new function specifically for DPAT
	@code Maxim::DPAT::DPAT(); @endcode

## Data Log ##
- Additional data logs will occur for every test added:
	@code
	- Test Value     : Test Number=Original Test Number + 1,000,000,000
	- DPAT Low Limit : Test Number=Original Test Number + 1,100,000,000 
	- DPAT High Limit: Test Number=Original Test Number + 1,200,000,000
	@endcode
- One DPAT test will be datalogged for overall status
	@code
	- DPAT: Test Number = 1,000,000,000
	@endcode
**************************************************************************************************************************************************************/

namespace Maxim
{
	namespace DPAT
	{
		void DPAT_add_test(int testnum,char* method,int initial_samples,int window_size,double sigma_scalar_low,double sigma_scalar_high);
		void DPAT_add_test(int testnum,char* method,int initial_samples,int window_size,double sigma_scalar);
		void DPAT_data(int iIndex, double value, int iSite);
		void DPAT();
		void DPAT_reset_stats();
		void DPAT_load_sheet(char* filename);
		void DPAT_enable(bool on_off);
		void DPAT_set_sample_bin(int iBin);
		__declspec(deprecated("Maxim::DPAT is now obsolete.\n  Please use Galaxy WS PAT for PROBE or PST_BUMP, https://confluence.maxim-ic.com/display/GLX/Galaxy+PAT+-+Sort .\n  For packaged parts, see https://confluence.maxim-ic.com/display/ETS88/ETS-88+Galaxy+FT+PAT")) void DPAT_enable(bool on_off);
	}
}