//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		MaximFuncLib.h                                                                           		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximFuncLib/MaximFuncLib.h $
*   Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*   Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:
*		Maxim library header file used to include all the other MaximLibFunc header files.  This is done so the Template only needs to #include one header file.
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History                                                    
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	MaximFuncLib.h
@brief	Maxim library header file used to include all the other MaximLibFunc header files.  This is done so the Template only needs to @#include one header file.
**************************************************************************************************************************************************************/

#ifndef MAXIMFUNCLIB_H
#define MAXIMFUNCLIB_H

#include "..\MaximLib\MaximLib.h"   // Some MaximFuncLib uses some items from MaximLib
#include "MaximFuncLib_System.h"	//Must come before some other files since it has class definitions that other files use
#include "MaximFuncLib_I2C.h"
#include "MaximFuncLib_OTP.h"
#include "MaximFuncLib_AWG.h"
#include "MaximFuncLib_Exec.h"	    // Provides event control for functions that need access to MaxFuncLib functions
#include "MaximFuncLib_Wafer.h" //Wafer related Functions

// Allows us to intercept functions that were originally defined in MaximLib and define them in MaximFuncLib
// This sets up a more structured/hierarchael approach for new and existing programs.
// One problem this solves is that old programs don't have MaximFuncLib, so we could not just define the functions in MaximFuncLib
#ifndef MAXIMFUNCLIB_LIB

#undef Lib_UserInit
#undef Lib_UserExit
#undef Lib_OnTestInitPre
#undef Lib_OnTestInitPost
#undef Lib_OnTestExitPre
#undef Lib_OnTestExitPost
#undef Lib_OnTestStartupPre
#undef Lib_OnTestStartupPost
#undef Lib_OnTestCompletionPrePowerDown
#undef Lib_OnTestCompletionPostPowerDown
#undef Lib_OnLogData
#undef Lib_OnFailSitePrePowerDown
#undef Lib_OnFailSitePostPowerDown
#undef Lib_OnSot
#undef Lib_OnUtilError
#undef Lib_OnInterlock

#define Lib_UserInit							Func::Lib_UserInit
#define Lib_UserExit							Func::Lib_UserExit
#define Lib_OnTestInitPre					Func::Lib_OnTestInitPre
#define Lib_OnTestInitPost					Func::Lib_OnTestInitPost
#define Lib_OnTestExitPre					Func::Lib_OnTestExitPre
#define Lib_OnTestExitPost					Func::Lib_OnTestExitPost
#define Lib_OnTestStartupPre					Func::Lib_OnTestStartupPre
#define Lib_OnTestStartupPost				Func::Lib_OnTestStartupPost
#define Lib_OnTestCompletionPrePowerDown		Func::Lib_OnTestCompletionPrePowerDown
#define Lib_OnTestCompletionPostPowerDown	Func::Lib_OnTestCompletionPostPowerDown
#define Lib_OnLogData						Func::Lib_OnLogData
#define Lib_OnFailSitePrePowerDown			Func::Lib_OnFailSitePrePowerDown
#define Lib_OnFailSitePostPowerDown			Func::Lib_OnFailSitePostPowerDown
#define Lib_OnSot							Func::Lib_OnSot
#define Lib_OnUtilError						Func::Lib_OnUtilError
#define Lib_OnInterlock						Func::Lib_OnInterlock

#endif

#endif
