//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib_Exec.h                                                                           		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximFuncLib/MaximFuncLib_Exec.h $
*	Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*	Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:
*		Maxim library header file for Test Control functions
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History                                                    
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE

/**********************************************************************************************************************************************For*Doxygen**//**
@file	Maximlib_Exec.h
@brief	Maxim library file for Test Control functions
**************************************************************************************************************************************************************/

#ifndef MAXIMFUNCLIB_EXEC_H
#define MAXIMFUNCLIB_EXEC_H

// The following declaration allows contact to be called in this function.
void Contact(int & DSIndex);

	namespace Maxim
	{
		namespace Exec
		{
			namespace Func
			{
				BOOL Lib_UserInit(int iNumSites, bool bLoadVector, bool bInitMeter = false, int iRealTimeDatalogSwitch = -1);
				BOOL Lib_UserExit();
				BOOL Lib_OnTestInitPre();
				BOOL Lib_OnTestInitPost();
				BOOL Lib_OnTestExitPre();
				BOOL Lib_OnTestExitPost();
				BOOL Lib_OnTestStartupPre(BOOL bTimeTests);
				BOOL Lib_OnTestStartupPost();
				BOOL Lib_OnTestCompletionPrePowerDown();
				BOOL Lib_OnTestCompletionPostPowerDown();
				BOOL Lib_OnLogData(int site, datalog_info_t& info);
				BOOL Lib_OnFailSitePrePowerDown(int site);
				BOOL Lib_OnFailSitePostPowerDown(int site);
				int Lib_OnSot(int SotValue, int UserSwitchSite0, int UserSwitchSiteMax, int UserIntLoopCount, int UserIntLoopDelayms, bool bCheckerPassed );
				BOOL Lib_OnUtilError(int errnum);
				BOOL Lib_OnInterlock(ULONG intlocks);
			}
		}
	}

		
#endif
