//DO NOT EDIT THIS FILE
/*** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-
*                                                                            
*	Source title:		Maximlib.CPP                                                                            		  
*	URL:				$URL: https://svn.maxim-ic.com/svn/ets/test_programs/AP89/AP89_FT/Trunk/MaximLib.cpp $
*   Last Modified by:	$LastChangedBy: govit.pimthong $                                       
*	Date:				$Date: 2017-03-09 12:55:55 +0700 (Thu, 09 Mar 2017) $                                                
*   Current Rev:		$Revision: 61735 $
*                                                                            
*	Description:  
*		Maxim library cpp file used to include all the other MaximLib cpp files.  
*       This is done so the Program only has one file in it that doesn't include code to make it more difficult to accidently change MaximLib files.
*		Maxim library written and maintained by:								 
*			Patrick Hayes (Patrick.Hayes@MaximIntegrated.com)	                 
*			Mark Bruening (Mark.Bruening@MaximIntegrated.com)                                                                            
*
*   Revision History:
*		See Maximlib_Exec.h file.
*                                                                            
**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****-**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
//DO NOT EDIT THIS FILE
#ifdef _DEBUG 
#define MAXIM_DEGLITCH							//comment to disable embedded Deglitch Assistant checks
#endif
#define MAXIMLIB_LIB 

#include "MaximLib\MaximLib.h"

#include "MaximLib\Maximlib_System.cpp"			//System functions
#include "MaximLib\Maximlib_Exec.cpp"			//Test Control functions
#include "MaximLib\MaximLib_Datalog.cpp"		//Maxim datalogging functions
#include "MaximLib\Maximlib_Datasheet.cpp"		//file for Eagle Datasheet functions
#include "MaximLib\Maximlib_Checker.cpp"		//Hardware Checker Functions
#include "MaximLib\Maximlib_DMM.cpp"			//HP Meter functions
#include "MaximLib\MaximLib_PinListData.cpp"    //PinListData definition
#include "MaximLib\MaximLib_SiteVar.cpp"		//SiteVar definition
#include "MaximLib\MaximLib_APU.cpp"			//APU functions
#include "MaximLib\MaximLib_CBIT.cpp"			//CBIT functions
#include "MaximLib\MaximLib_DPIN.cpp"			//DPIN functions
#include "MaximLib\MaximLib_TMU.cpp"			//TMU functions
#include "MaximLib\MaximLib_SPU.cpp"			//SPU functions
#include "MaximLib\MaximLib_Deglitch.cpp"		//Deglitch functions
#include "MaximLib\MaximLib_DPAT.cpp"			//DPAT functions
#include "MaximLib\MaximLib_Results.cpp"		//Code to get prior results
#include "MaximLib\MaximLib_PinMap.cpp"		    //PinMap functions
//#include "MaximLib\MaximLib_Galaxy.cpp"			//Galaxy functions


